import type { ElementKind, RelationKind } from "@/parser/types";
import type { DiagramView } from "@/stores/view.store";

export interface SysmlNodeMapping {
  kind: ElementKind;
  label: string;
  icon: string;
  shape: "package" | "part" | "requirement" | "interface" | "action" | "state" | "connection" | "case" | "usecase" | "view" | "calculation" | "metadata" | "annotation" | "stakeholder" | "default" | "circle";
  family: "structure" | "interface" | "behavior" | "requirement" | "constraint" | "analysis" | "metadata" | "annotation";
  role:
    | "container"
    | "primary"
    | "instance"
    | "definition"
    | "usage"
    | "member"
    | "control"
    | "actor"
    | "stakeholder";
  defaultViews: DiagramView[];
  bg: string;
  border: string;
  header: string;
  headerText: string;
  renderMode: "container" | "definition" | "usage" | "member" | "control" | "annotation";
  compartments?: Array<{
    key: string;
    title: string;
  }>;
}

export interface SysmlEdgeMapping {
  kind: RelationKind;
  label: string;
  family: "ownership" | "interaction" | "requirement" | "behavior" | "organization" | "typing";
  defaultViews: DiagramView[];
  stroke: string;
  dashed?: boolean;
  marker?: "block" | "open" | "none";
}

export const SYSML_NODE_MAPPING: Record<ElementKind, SysmlNodeMapping> = {
  package: {
    kind: "package",
    label: "包",
    icon: "📁",
    family: "structure",
    shape: "package",
    role: "container",
    defaultViews: ["general", "requirements"],
    bg: "#F0F4FA",
    border: "#5B9BD5",
    header: "#5B9BD5",
    headerText: "#fff",
    renderMode: "container",
    compartments: [
      { key: "members", title: "members" },
      { key: "imports", title: "imports" },
      { key: "dependencies", title: "dependencies" },
    ],
  },
  partDef: {
    kind: "partDef",
    label: "部件定义",
    icon: "■",
    family: "structure",
    shape: "part",
    role: "primary",
    defaultViews: ["general", "ibd", "requirements"],
    bg: "#F0F7F0",
    border: "#388A34",
    header: "#388A34",
    headerText: "#fff",
    renderMode: "definition",
    compartments: [
      { key: "attributes", title: "attributes" },
      { key: "ports", title: "ports" },
      { key: "behaviors", title: "behaviors" },
      { key: "parts", title: "parts" },
    ],
  },
  partUsage: {
    kind: "partUsage",
    label: "部件",
    icon: "□",
    family: "structure",
    shape: "part",
    role: "instance",
    defaultViews: ["ibd", "requirements"],
    bg: "#F7FBF4",
    border: "#5CB85C",
    header: "#5CB85C",
    headerText: "#fff",
    renderMode: "usage",
    compartments: [
      { key: "attributes", title: "attributes" },
      { key: "ports", title: "ports" },
      { key: "behaviors", title: "behaviors" },
      { key: "parts", title: "parts" },
    ],
  },
  itemDef: {
    kind: "itemDef",
    label: "物件定义",
    icon: "◇",
    family: "structure",
    shape: "default",
    role: "definition",
    defaultViews: ["general", "behavior"],
    bg: "#F5F5F5",
    border: "#636B7B",
    header: "#636B7B",
    headerText: "#fff",
    renderMode: "definition",
  },
  itemUsage: {
    kind: "itemUsage",
    label: "物件",
    icon: "◇",
    family: "structure",
    shape: "default",
    role: "usage",
    defaultViews: ["behavior"],
    bg: "#FAFBFC",
    border: "#9CA3AF",
    header: "#9CA3AF",
    headerText: "#fff",
    renderMode: "usage",
  },
  portDef: {
    kind: "portDef",
    label: "端口定义",
    icon: "◎",
    family: "interface",
    shape: "default",
    role: "definition",
    defaultViews: ["general"],
    bg: "#F0F5FA",
    border: "#3B7DD8",
    header: "#3B7DD8",
    headerText: "#fff",
    renderMode: "definition",
  },
  portUsage: {
    kind: "portUsage",
    label: "端口",
    icon: "◎",
    family: "interface",
    shape: "default",
    role: "usage",
    defaultViews: ["ibd"],
    bg: "#E8F0FE",
    border: "#3B7DD8",
    header: "#3B7DD8",
    headerText: "#fff",
    renderMode: "usage",
  },
  connectionDef: {
    kind: "connectionDef",
    label: "连接定义",
    icon: "◇",
    family: "interface",
    shape: "connection",
    role: "definition",
    defaultViews: ["general"],
    bg: "#F5F0F7",
    border: "#7B4EA3",
    header: "#7B4EA3",
    headerText: "#fff",
    renderMode: "definition",
    compartments: [
      { key: "ends", title: "ends" },
      { key: "ports", title: "ports" },
    ],
  },
  requirementDef: {
    kind: "requirementDef",
    label: "需求定义",
    icon: "📋",
    family: "requirement",
    shape: "requirement",
    role: "definition",
    defaultViews: ["requirements", "general"],
    bg: "#FDFAF0",
    border: "#B8860B",
    header: "#B8860B",
    headerText: "#fff",
    renderMode: "definition",
    compartments: [
      { key: "text", title: "text" },
      { key: "subject", title: "subject" },
      { key: "constraints", title: "constraints" },
      { key: "relations", title: "relations" },
    ],
  },
  requirementUsage: {
    kind: "requirementUsage",
    label: "需求",
    icon: "📄",
    family: "requirement",
    shape: "requirement",
    role: "usage",
    defaultViews: ["requirements"],
    bg: "#FFFDF5",
    border: "#D4A017",
    header: "#D4A017",
    headerText: "#fff",
    renderMode: "usage",
    compartments: [
      { key: "text", title: "text" },
      { key: "subject", title: "subject" },
      { key: "constraints", title: "constraints" },
      { key: "relations", title: "relations" },
    ],
  },
  interfaceDef: {
    kind: "interfaceDef",
    label: "接口定义",
    icon: "○",
    family: "interface",
    shape: "interface",
    role: "definition",
    defaultViews: ["general", "ibd"],
    bg: "#F8F2F8",
    border: "#9B59B6",
    header: "#9B59B6",
    headerText: "#fff",
    renderMode: "definition",
    compartments: [
      { key: "ends", title: "ends" },
      { key: "ports", title: "ports" },
      { key: "features", title: "features" },
    ],
  },
  interfaceUsage: {
    kind: "interfaceUsage",
    label: "接口",
    icon: "○",
    family: "interface",
    shape: "interface",
    role: "usage",
    defaultViews: ["ibd"],
    bg: "#FBF7FC",
    border: "#B184C4",
    header: "#B184C4",
    headerText: "#fff",
    renderMode: "usage",
  },
  actionDef: {
    kind: "actionDef",
    label: "动作定义",
    icon: "▶",
    family: "behavior",
    shape: "action",
    role: "definition",
    defaultViews: ["behavior"],
    bg: "#FDF2F2",
    border: "#C0392B",
    header: "#C0392B",
    headerText: "#fff",
    renderMode: "definition",
    compartments: [
      { key: "parameters", title: "parameters" },
      { key: "messaging", title: "send/accept" },
      { key: "flows", title: "flow" },
      { key: "successions", title: "succession" },
    ],
  },
  actionUsage: {
    kind: "actionUsage",
    label: "动作",
    icon: "▷",
    family: "behavior",
    shape: "action",
    role: "usage",
    defaultViews: ["behavior"],
    bg: "#FFF7F7",
    border: "#D9534F",
    header: "#D9534F",
    headerText: "#fff",
    renderMode: "usage",
    compartments: [
      { key: "parameters", title: "parameters" },
      { key: "messaging", title: "send/accept" },
      { key: "flows", title: "flow" },
      { key: "successions", title: "succession" },
    ],
  },
  stateDef: {
    kind: "stateDef",
    label: "状态定义",
    icon: "◐",
    family: "behavior",
    shape: "state",
    role: "definition",
    defaultViews: ["behavior"],
    bg: "#F0F6F7",
    border: "#2E86AB",
    header: "#2E86AB",
    headerText: "#fff",
    renderMode: "definition",
    compartments: [
      { key: "actions", title: "state actions" },
      { key: "states", title: "states" },
      { key: "transitions", title: "transitions" },
    ],
  },
  stateUsage: {
    kind: "stateUsage",
    label: "状态",
    icon: "◐",
    family: "behavior",
    shape: "state",
    role: "usage",
    defaultViews: ["behavior"],
    bg: "#F6FBFC",
    border: "#5EA5C2",
    header: "#5EA5C2",
    headerText: "#fff",
    renderMode: "usage",
    compartments: [
      { key: "actions", title: "state actions" },
      { key: "states", title: "states" },
      { key: "transitions", title: "transitions" },
    ],
  },
  constraintDef: {
    kind: "constraintDef",
    label: "约束定义",
    icon: "🔒",
    family: "constraint",
    shape: "default",
    role: "definition",
    defaultViews: ["requirements", "behavior"],
    bg: "#F3F4F6",
    border: "#4B5563",
    header: "#4B5563",
    headerText: "#fff",
    renderMode: "definition",
  },
  constraintUsage: {
    kind: "constraintUsage",
    label: "约束",
    icon: "🔒",
    family: "constraint",
    shape: "default",
    role: "usage",
    defaultViews: ["requirements", "behavior"],
    bg: "#FAFBFC",
    border: "#9CA3AF",
    header: "#9CA3AF",
    headerText: "#fff",
    renderMode: "usage",
  },
  attribute: {
    kind: "attribute",
    label: "属性",
    icon: "⬡",
    family: "structure",
    shape: "default",
    role: "member",
    defaultViews: [],
    bg: "#F9FAFB",
    border: "#9CA3AF",
    header: "#4B5563",
    headerText: "#fff",
    renderMode: "member",
  },
  operation: {
    kind: "operation",
    label: "操作",
    icon: "⚙",
    family: "structure",
    shape: "default",
    role: "member",
    defaultViews: [],
    bg: "#F0F2F8",
    border: "#5B6ABF",
    header: "#5B6ABF",
    headerText: "#fff",
    renderMode: "member",
  },
  port: {
    kind: "port",
    label: "端口",
    icon: "◎",
    family: "interface",
    shape: "default",
    role: "member",
    defaultViews: ["ibd"],
    bg: "#E8F0FE",
    border: "#3B7DD8",
    header: "#3B7DD8",
    headerText: "#fff",
    renderMode: "member",
  },
  controlNode: {
    kind: "controlNode",
    label: "控制节点",
    icon: "●",
    family: "behavior",
    shape: "circle",
    role: "control",
    defaultViews: ["behavior"],
    bg: "#F8FAFC",
    border: "#64748B",
    header: "#64748B",
    headerText: "#fff",
    renderMode: "control",
  },
  useCaseDef: {
    kind: "useCaseDef",
    label: "用例定义",
    icon: "◈",
    family: "behavior",
    shape: "usecase",
    role: "definition",
    defaultViews: ["general", "behavior"],
    bg: "#F5F2F9",
    border: "#A855F7",
    header: "#A855F7",
    headerText: "#fff",
    renderMode: "definition",
  },
  useCaseUsage: {
    kind: "useCaseUsage",
    label: "用例",
    icon: "◈",
    family: "behavior",
    shape: "usecase",
    role: "usage",
    defaultViews: ["behavior"],
    bg: "#FAF8FC",
    border: "#D8B4FE",
    header: "#D8B4FE",
    headerText: "#fff",
    renderMode: "usage",
  },
  calculationDef: {
    kind: "calculationDef",
    label: "计算定义",
    icon: "∑",
    family: "analysis",
    shape: "default",
    role: "definition",
    defaultViews: ["behavior"],
    bg: "#F0F4FA",
    border: "#4F46E5",
    header: "#4F46E5",
    headerText: "#fff",
    renderMode: "definition",
    compartments: [
      { key: "parameters", title: "parameters" },
      { key: "expression", title: "expression" },
    ],
  },
  calculationUsage: {
    kind: "calculationUsage",
    label: "计算",
    icon: "∑",
    family: "analysis",
    shape: "default",
    role: "usage",
    defaultViews: ["behavior"],
    bg: "#F8FAFC",
    border: "#9CA3AF",
    header: "#9CA3AF",
    headerText: "#fff",
    renderMode: "usage",
  },
  caseDef: {
    kind: "caseDef",
    label: "用例定义",
    icon: "▦",
    family: "analysis",
    shape: "case",
    role: "definition",
    defaultViews: ["requirements"],
    bg: "#FEF3F2",
    border: "#EA5455",
    header: "#EA5455",
    headerText: "#fff",
    renderMode: "definition",
  },
  analysisCaseDef: {
    kind: "analysisCaseDef",
    label: "分析用例",
    icon: "▥",
    family: "analysis",
    shape: "case",
    role: "definition",
    defaultViews: ["requirements", "behavior"],
    bg: "#FEF3F2",
    border: "#F29E38",
    header: "#F29E38",
    headerText: "#fff",
    renderMode: "definition",
  },
  verificationCaseDef: {
    kind: "verificationCaseDef",
    label: "验证用例",
    icon: "▤",
    family: "analysis",
    shape: "case",
    role: "definition",
    defaultViews: ["requirements"],
    bg: "#FEF3F2",
    border: "#57A773",
    header: "#57A773",
    headerText: "#fff",
    renderMode: "definition",
  },
  viewDef: {
    kind: "viewDef",
    label: "视图定义",
    icon: "▢",
    family: "structure",
    shape: "default",
    role: "definition",
    defaultViews: ["general"],
    bg: "#F5F5F5",
    border: "#636B7B",
    header: "#636B7B",
    headerText: "#fff",
    renderMode: "definition",
  },
  viewUsage: {
    kind: "viewUsage",
    label: "视图",
    icon: "▢",
    family: "structure",
    shape: "default",
    role: "usage",
    defaultViews: ["general"],
    bg: "#FAFBFC",
    border: "#9CA3AF",
    header: "#9CA3AF",
    headerText: "#fff",
    renderMode: "usage",
  },
  viewpointDef: {
    kind: "viewpointDef",
    label: "视点定义",
    icon: "◆",
    family: "structure",
    shape: "default",
    role: "definition",
    defaultViews: ["general"],
    bg: "#F5F5F5",
    border: "#636B7B",
    header: "#636B7B",
    headerText: "#fff",
    renderMode: "definition",
  },
  viewpointUsage: {
    kind: "viewpointUsage",
    label: "视点",
    icon: "◆",
    family: "structure",
    shape: "default",
    role: "usage",
    defaultViews: ["general"],
    bg: "#FAFBFC",
    border: "#9CA3AF",
    header: "#9CA3AF",
    headerText: "#fff",
    renderMode: "usage",
  },
  renderingDef: {
    kind: "renderingDef",
    label: "渲染定义",
    icon: "▨",
    family: "structure",
    shape: "default",
    role: "definition",
    defaultViews: ["general"],
    bg: "#F5F5F5",
    border: "#636B7B",
    header: "#636B7B",
    headerText: "#fff",
    renderMode: "definition",
  },
  metadataDef: {
    kind: "metadataDef",
    label: "元数据定义",
    icon: "⚙",
    family: "metadata",
    shape: "default",
    role: "definition",
    defaultViews: ["general"],
    bg: "#F3F4F6",
    border: "#4B5563",
    header: "#4B5563",
    headerText: "#fff",
    renderMode: "definition",
  },
  comment: {
    kind: "comment",
    label: "注释",
    icon: "💬",
    family: "annotation",
    shape: "annotation",
    role: "member",
    defaultViews: ["general", "requirements", "behavior"],
    bg: "#FFFAF0",
    border: "#F97316",
    header: "#F97316",
    headerText: "#fff",
    renderMode: "annotation",
  },
  documentation: {
    kind: "documentation",
    label: "文档",
    icon: "📄",
    family: "annotation",
    shape: "annotation",
    role: "member",
    defaultViews: ["general", "requirements", "behavior"],
    bg: "#FEFCE8",
    border: "#CA8A04",
    header: "#CA8A04",
    headerText: "#fff",
    renderMode: "annotation",
  },
  textualRepresentation: {
    kind: "textualRepresentation",
    label: "文本表示",
    icon: "📝",
    family: "annotation",
    shape: "annotation",
    role: "member",
    defaultViews: ["general", "requirements", "behavior"],
    bg: "#F0FDF4",
    border: "#22C55E",
    header: "#22C55E",
    headerText: "#fff",
    renderMode: "annotation",
  },
  subject: {
    kind: "subject",
    label: "主体",
    icon: "👤",
    family: "structure",
    shape: "default",
    role: "member",
    defaultViews: ["requirements"],
    bg: "#F3F4F6",
    border: "#4B5563",
    header: "#4B5563",
    headerText: "#fff",
    renderMode: "member",
  },
  stakeholder: {
    kind: "stakeholder",
    label: "利益相关者",
    icon: "👥",
    family: "structure",
    shape: "default",
    role: "stakeholder",
    defaultViews: ["requirements"],
    bg: "#F3F4F6",
    border: "#4B5563",
    header: "#4B5563",
    headerText: "#fff",
    renderMode: "member",
  },
  attributeUsage: {
    kind: "attributeUsage",
    label: "属性使用",
    icon: "⬢",
    family: "structure",
    shape: "default",
    role: "member",
    defaultViews: [],
    bg: "#F9FAFB",
    border: "#9CA3AF",
    header: "#4B5563",
    headerText: "#fff",
    renderMode: "member",
  },
};

export const SYSML_EDGE_MAPPING: Record<RelationKind, SysmlEdgeMapping> = {
  containment: {
    kind: "containment",
    label: "包含",
    family: "ownership",
    defaultViews: ["general", "requirements"],
    stroke: "#B2BFCE",
    marker: "none",
  },
  specialization: {
    kind: "specialization",
    label: "特化",
    family: "typing",
    defaultViews: ["general"],
    stroke: "#374151",
    marker: "block",
  },
  subsetting: {
    kind: "subsetting",
    label: "子集化",
    family: "typing",
    defaultViews: ["general"],
    stroke: "#2E86AB",
    marker: "block",
  },
  redefinition: {
    kind: "redefinition",
    label: "重定义",
    family: "typing",
    defaultViews: ["general"],
    stroke: "#C0392B",
    marker: "block",
  },
  dependency: {
    kind: "dependency",
    label: "依赖",
    family: "organization",
    defaultViews: ["general"],
    stroke: "#9CA3AF",
    dashed: true,
    marker: "open",
  },
  import: {
    kind: "import",
    label: "导入",
    family: "organization",
    defaultViews: ["general"],
    stroke: "#5B9BD5",
    dashed: true,
    marker: "open",
  },
  expose: {
    kind: "expose",
    label: "公开",
    family: "organization",
    defaultViews: ["general"],
    stroke: "#5B5BA5",
    dashed: true,
    marker: "block",
  },
  connection: {
    kind: "connection",
    label: "连接",
    family: "interaction",
    defaultViews: ["ibd"],
    stroke: "#636B7B",
    marker: "block",
  },
  binding: {
    kind: "binding",
    label: "绑定",
    family: "interaction",
    defaultViews: ["ibd"],
    stroke: "#D4A017",
    marker: "block",
  },
  flow: {
    kind: "flow",
    label: "流",
    family: "behavior",
    defaultViews: ["behavior", "ibd"],
    stroke: "#2E8B57",
    marker: "block",
  },
  succession: {
    kind: "succession",
    label: "顺序",
    family: "behavior",
    defaultViews: ["behavior"],
    stroke: "#636B7B",
    dashed: true,
    marker: "open",
  },
  perform: {
    kind: "perform",
    label: "执行",
    family: "behavior",
    defaultViews: ["behavior"],
    stroke: "#C0392B",
    marker: "block",
  },
  exhibit: {
    kind: "exhibit",
    label: "展示",
    family: "behavior",
    defaultViews: ["behavior"],
    stroke: "#2E86AB",
    marker: "block",
  },
  transition: {
    kind: "transition",
    label: "转移",
    family: "behavior",
    defaultViews: ["behavior"],
    stroke: "#2E86AB",
    marker: "open",
  },
  accept: {
    kind: "accept",
    label: "接收",
    family: "behavior",
    defaultViews: ["behavior"],
    stroke: "#0F766E",
    marker: "open",
  },
  send: {
    kind: "send",
    label: "发送",
    family: "behavior",
    defaultViews: ["behavior"],
    stroke: "#7C3AED",
    marker: "block",
  },
  satisfy: {
    kind: "satisfy",
    label: "满足",
    family: "requirement",
    defaultViews: ["requirements"],
    stroke: "#C2397A",
    dashed: true,
    marker: "open",
  },
  require: {
    kind: "require",
    label: "要求",
    family: "requirement",
    defaultViews: ["requirements"],
    stroke: "#D97706",
    dashed: true,
    marker: "open",
  },
  verify: {
    kind: "verify",
    label: "验证",
    family: "requirement",
    defaultViews: ["requirements"],
    stroke: "#5B6ABF",
    dashed: true,
    marker: "open",
  },
  allocate: {
    kind: "allocate",
    label: "分配",
    family: "requirement",
    defaultViews: ["general"],
    stroke: "#B5598B",
    dashed: true,
    marker: "block",
  },
  annotate: {
    kind: "annotate",
    label: "注解",
    family: "organization",
    defaultViews: ["general", "requirements", "behavior"],
    stroke: "#9CA3AF",
    dashed: true,
    marker: "open",
  },
  reference: {
    kind: "reference",
    label: "引用",
    family: "typing",
    defaultViews: ["general"],
    stroke: "#7B8798",
    marker: "block",
  },
};

export const SYSML_VIEW_MAPPING: Record<
  DiagramView,
  { nodeWhitelist: ElementKind[]; edgeWhitelist: RelationKind[] }
> = {
  general: {
    nodeWhitelist: [
      "package",
      "partDef",
      "itemDef",
      "portDef",
      "connectionDef",
      "interfaceDef",
      "requirementDef",
      "viewDef",
      "viewpointDef",
      "renderingDef",
      "comment",
      "documentation",
    ],
    edgeWhitelist: [
      "containment",
      "specialization",
      "dependency",
      "reference",
      "import",
      "expose",
      "redefinition",
      "subsetting",
      "annotate",
      "allocate",
    ],
  },
  ibd: {
    nodeWhitelist: [
      "package",
      "partDef",
      "partUsage",
      "interfaceDef",
      "interfaceUsage",
      "portDef",
      "portUsage",
      "connectionDef",
    ],
    edgeWhitelist: ["connection", "binding", "flow", "annotate"],
  },
  requirements: {
    nodeWhitelist: [
      "package",
      "requirementDef",
      "requirementUsage",
      "partDef",
      "partUsage",
      "constraintDef",
      "constraintUsage",
      "caseDef",
      "analysisCaseDef",
      "verificationCaseDef",
      "subject",
      "stakeholder",
      "comment",
      "documentation",
    ],
    edgeWhitelist: ["containment", "satisfy", "require", "verify", "annotate", "allocate"],
  },
  behavior: {
    nodeWhitelist: [
      "actionDef",
      "actionUsage",
      "stateDef",
      "stateUsage",
      "itemDef",
      "itemUsage",
      "controlNode",
      "partDef",
      "partUsage",
      "useCaseDef",
      "useCaseUsage",
      "calculationDef",
      "calculationUsage",
      "analysisCaseDef",
      "comment",
      "documentation",
    ],
    edgeWhitelist: ["flow", "succession", "perform", "exhibit", "transition", "accept", "send", "annotate"],
  },
};
